### ISSUE TITLE
Issues Running Golf and Golf Setup

### ISSUE THREAD

**Issue by agbala** [zhusj/baxter_servoing_example#1]
Greetings,
I am working with a Baxter Research robot and I am attempting to run the Visual Servoing example that is provided at http://sdk.rethinkkrobotics.com/wiki/Worked_Example_Visual_Servoing  After running all the installation procedure code given, I am attempting to run the golf_setup.py. When I do so, I get an error in the output that states:

[INFO] [WallTime: 1464727467.182032] Robot Enabled
PASS: Valid joint configuration found
             request   actual
front back = 0.6000  0.6009
left right = 0.2000  0.2000
up down    = 0.1500  0.1500
roll       = -3.1416  3.1401
pitch      = 0.0000  0.0028
yaw        = 0.0000  0.0106
distance =  0.352
terminate called after throwing an instance of 'boost::exception_detail::clone_implboost::exception_detail::error_info_injector<boost::lock_error >'
  what():  boost: mutex lock failed in pthread_mutex_lock: Invalid argument
Aborted (core dumped)

To try to correct this issue, I tried performing an update of my boost libraries, but I found out I had the latest supported version on Ubuntu.  I also made all the changes that were cited on this repository, and I still received the same error. 

Ignoring the boost error, I continued into running the golf program, and I encountered the output:
Traceback (most recent call last):
    File "home/baxter/ros_ws/src/activerobots/src/golf.py", line 38, in <module>
       import cv
    File "usr/local/lib/python2.7/dist-packages/cv.py", line 1, in <module>
       from cv2.cv import *
ImportError: No module named cv

I tried to install opencv, as that was one solution I found when googling the error, but that did not work.

Any help is greatly appreciated.

**Comment by zhusj** [comment]
@agbala I don't remember which version of boost I was using. But since the example is a few years old, I suspect the latest version may not be supported.

Your second problem is definitely opencv-python library related. Are you using OpenCV 3(I think this code is meant to work with OpenCV 2)? 

Try just "import cv" as a sanity check and resolve that first.
